- name: Deploy to Tomcat
  hosts: web
  become: yes
  
  tasks:
  - name: Copy to Tomcat
  	copy:
  	  src: '/'
  	  dest: "/opt/tomcat/webapps/MyAnsibleApp02.war"
  	  remote_src: no
  	  
  - name: Restart tomcat
  	systemd:
  	  	name: tomcat
  	  	state: restarted
