- name: Deploy to Tomcat
  hosts: web
  become: yes

  tasks:
    - name: Copy to Tomcat
      copy:
        src: '/var/snap/jenkins/4865/workspace/ansible2.0/target/MyAnsibleApp02.war'
        dest: "/opt/tomcat/webapps/MyAnsibleApp02.war"
        remote_src: no

    - name: Restart tomcat
      systemd:
        name: tomcat
        state: restarted
